#pragma once
#include <cstdint>

namespace MetaModule
{
// hardware_random is a true random number generated by hardware with an analog entropy source.
// On average, it's about 2-3x slower than calling random()
//
// Usage:
// if (MetaModule::hardware_random_ready())
//     val = MetaModule::hardware_random();
//
bool hardware_random_ready();
uint32_t hardware_random();

// random() returns a pseudo-random number
uint32_t random();

} // namespace MetaModule
//
